spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:32769/middle
    username: root
    password: boom

cloud:
  aws:
    region:
      static: us-east-1

incoming:
  name: ${INCOMING_NAME:create}

outgoing:
  topic: ${OUTGOING_TOPIC:created}